services:
  - type: web
    name: plant-medicator-backend
    runtime: python
    python:
      version: "3.11.8"
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000  # Render recomienda este puerto por defecto
      - key: ENV
        value: production
      - key: SECRET_KEY
        generateValue: true  # Mejor práctica para claves secretas
      - key: OPENAI_API_KEY
        value: your-actual-key-here  # Añade esto si usas OpenAI
